version: 2

models:
  - name: customers
    description: One record per customer
    columns:
      - name: customer_id
        description: Primary Key
        data_tests:
          - unique
          - not_null
      - name: first_order_date
        description: The first order of the customer. NULL when the customer has not yet placed an order.
  
  - name: stg_customers
    description: This model cleans up the customer data.
    columns:
      - name: customer_id
        description: Primary Key
        data_tests:
          - unique
          - not_null

  - name: stg_orders
    description: This model cleans up the order data.
    columns:
      - name: order_id
        description: Primary Key
        data_tests:
          - unique
          - not_null
      - name: status
        data_tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        data_tests:
          - not_null
          - relationships:
              field: customer_id
              to: ref('stg_customers')